### ISSUE TITLE
Unable to install python-javabridge

### ISSUE THREAD

**Issue by sumitgarai** [CellProfiler/python-javabridge#16]
Hi! 

I have been trying to install python-javabridge in order to compile CellProfiler, but it throws up an error.

` ERROR: Command errored out with exit status 1:
     command: /home/sumit/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-if_onu76/python-javabridge_387671473cdc4677a98abd9c06105664/setup.py'"'"'; __file__='"'"'/tmp/pip-install-if_onu76/python-javabridge_387671473cdc4677a98abd9c06105664/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q50e9u59
         cwd: /tmp/pip-install-if_onu76/python-javabridge_387671473cdc4677a98abd9c06105664/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-if_onu76/python-javabridge_387671473cdc4677a98abd9c06105664/setup.py", line 412, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-install-if_onu76/python-javabridge_387671473cdc4677a98abd9c06105664/setup.py", line 142, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/home/sumit/anaconda3/lib/python3.8/posixpath.py", line 152, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5e/d5/78f75ee0a6beb51a606c50cc17d8f99782653f04dce6d5e12feaef089692/python-javabridge-4.0.3.tar.gz#sha256=3fee0c235efcfe866f95695fdc0b6289eab2371043b32ff4ca6feff098de59c5 (from https://pypi.org/simple/python-javabridge/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Any idea how could I fix it?

Thanks!

**Comment by zhujiajunbryan** [comment]
got same issue, wired..

**Comment by phamquiluan** [comment]
same issue

**Comment by leorrose** [comment]
same issue
