### ISSUE TITLE
Mac OSX Can't run Java > 1.6 applications

### ISSUE THREAD

**Issue by er432** [CellProfiler/python-javabridge#25]
On my Mac OSX v 10.9.4  system, I am unable to use javabridge with applications requiring Java version >= 7, getting the following error:

Exception in thread "Thread-2" java.lang.UnsupportedClassVersionError: net/maizegenetics/dna/WHICH_ALLELE : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

I tried making libraries point to an updated JDK, but the issue seems to stem from the JNI and the JavaVM file, which I'm not sure how to (or if it's possible) to migrate above v. 6. Any suggestions?

**Comment by LeeKamentsky** [comment]
You were very right. I have reworked things so that on OS/X, we find Java as you indicate above and use the include files there. In addition, we follow suggestions from @dscho in https://github.com/imagej/imagej-launcher (although I go looking for the .dylibs to load using "find"). We load the libraries using dlopen prior to the actual call to JNI_CreateJavaVM in order to explicitly pick the JVM.

**Comment by dscho** [comment]
> extra_link_args += ['-Wl,-rpath,%s' % os.path.join(java_home,'jre','lib','server')]

Hmm, this makes the build product unportable, i.e. you cannot simply ship the compiled library to other computers and expect it to work because `java_home` depends on the Java version that is installed on the computer, correct?

**Comment by LeeKamentsky** [comment]
Where did you see that line, @dscho ?

**Comment by LeeKamentsky** [comment]
Oops - the extra_link_args is something I didn't copy.
