### ISSUE TITLE
Proper usage of class_path

### ISSUE THREAD

**Issue by CatherineH** [CellProfiler/python-javabridge#70]
Hi, 

I'm trying to use the class_path variable, but it's not working as expected. I'm just wondering if I'm doing things correctly. My code is:

```
import javabridge
javabridge.start_vm(run_headless=True, class_path="/usr/share/libreoffice/help/en-US/simpress.jar")
print javabridge.run_script('java.lang.String.format("Hello, %s!", greetee);', dict(greetee='world'))
javabridge.kill_vm()
```

This results in the error:

```
Failed to get class org/mozilla/javascript/Context
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/mozilla/javascript/Context
Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.Context
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Traceback (most recent call last):
  File "java_test2.py", line 3, in <module>
    print javabridge.run_script('java.lang.String.format("Hello, %s!", greetee);', dict(greetee='world'))
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 334, in run_script
    "()Lorg/mozilla/javascript/Context;")
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 902, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 876, in make_static_call
    raise JavaException(jexception)
javabridge.jutil.JavaException: org/mozilla/javascript/Context
```
I thought that maybe this was caused by not also adding the jars that javabridge needs to run, so I also tried:
```
jars = javabridge.JARS
jars.append('/usr/share/libreoffice/help/en-US/simpress.jar')
import_string = ":".join(jars)
javabridge.start_vm(run_headless=True, class_path=import_string)
```
but I get the same error.

**Comment by LeeKamentsky** [comment]
Np - you are pretty close. Try this:

    class_path = javabridge.JARS + ['/usr/share/libreoffice/help/en-US/simpress.jar']
   javabridge.start_vm(run_headless=True, class_path=class_path)

You need to pass class_path a list of strings. Hope this helps, good luck, enjoy. Feel free to reopen if you need help on class_path or file another issue if you have other sorts of problems.
